// Generated by CoffeeScript 1.3.1

(function(document) {
  if (document["HouseholdLocation-latitude"]) {
    return emit(document.MalariaCaseID, {
      latitude: document["HouseholdLocation-latitude"],
      longitude: document["HouseholdLocation-longitude"],
      timestamp: document["HouseholdLocation-timestamp"]
    });
  }
});
