// Generated by CoffeeScript 1.6.3
var API;

API = {
  home: function() {
    App.Controller.displayScanner();
  },
  registration: function(user) {
    App.Controller.displayRegistration(user);
  },
  userScan: function(user) {
    App.Controller.displayScanner("user");
  },
  userMain: function() {
    App.Controller.displayUserMain();
  },
  userRegistration: function() {
    API.registration("user");
  },
  postUserRegistrationMenu: function() {
    App.Controller.postUserRegistrationMenu();
  },
  displayReportMenu: function() {
    App.Controller.displayReportMenu();
  },
  displayImmunization: function() {
    App.Controller.displayImmunization();
  },
  saveRecord: function(record) {
    App.Controller.saveRecord(record);
  }
};
