// Generated by CoffeeScript 1.6.3
var Controller;

Controller = {
  displayScanner: function(user) {
    var staticView;
    staticView = void 0;
    if (typeof user !== "undefined") {
      staticView = new VerifyView({
        template: JST["_attachments/templates/ScanVerifyView.handlebars"]
      });
    } else {
      staticView = new VerifyView({
        template: JST["_attachments/templates/VerifyView.handlebars"]
      });
    }
    Coconut.mainRegion.show(staticView);
  },
  displayRegistration: function(user) {
    $("#message").html("");
    if (typeof user !== "undefined") {
      return Coconut.router.navigate("#new/result/Individual%20Registration", true);
    } else {
      return Coconut.router.navigate("#new/result/Admin%20Registration", true);
    }
  },
  displayUserMain: function() {
    var staticView;
    $("#message").html("");
    staticView = new UserMainView();
    Coconut.mainRegion.show(staticView);
  },
  postUserRegistrationMenu: function() {
    var staticView;
    $("#message").html("");
    staticView = new UserMainView({
      template: JST["_attachments/templates/PostUserRegistrationMenuView.handlebars"]
    });
    Coconut.mainRegion.show(staticView);
  },
  displayReportMenu: function() {
    var staticView;
    $("#message").html("");
    staticView = new UserFormView({
      template: JST["_attachments/templates/UserReportMenu.handlebars"]
    });
    Coconut.mainRegion.show(staticView);
  },
  displayImmunization: function() {
    var staticView;
    $("#message").html("");
    staticView = new UserFormView({
      template: "ImmunizationForm"
    });
    Coconut.mainRegion.show(staticView);
  },
  saveRecord: function(record) {
    $("#message").html("");
    record = new Record(record);
    record.post();
    console.log('saved' + JSON.stringify(record));
    Coconut.trigger("userMain");
  }
};
