// Generated by CoffeeScript 1.6.3
var deferred, fetchTranslation, langChoice, user;

window.polyglot = new Polyglot();

window.polyglot.extend({
  "Home": "Início"
});

Handlebars.registerHelper('polyglot', function(phrase) {
  return window.polyglot.t(phrase);
});

fetchTranslation = function(languge) {
  var deferred, translation;
  deferred = $.Deferred();
  translation = new Translation({
    _id: languge
  });
  translation.fetch({
    success: function(record) {
      var json;
      json = record.toJSON();
      window.polyglot = new Polyglot();
      window.polyglot.extend(json);
      Handlebars.registerHelper('polyglot', function(phrase) {
        return window.polyglot.t(phrase);
      });
      return deferred.resolve();
    },
    error: function(error, response) {
      return console.log("Unable to fetch translation for " + " languge:" + languge + " model:" + JSON.stringify(error) + " response: " + response);
    }
  });
  return deferred.promise();
};

user = new User({
  _id: "user.admin"
});

user.fetch({
  success: function() {
    var langChoice;
    langChoice = user.get('langChoice');
    console.log("langChoice from doc: " + user.get('langChoice'));
    if (!langChoice) {
      langChoice = 'pt';
      user.set('langChoice', langChoice);
      return user.save({
        success: function() {
          return console.log("langChoice saved: " + langChoice);
        },
        error: function(json, msg) {
          return console.log("Error saving langChoice  " + msg);
        }
      });
    }
  },
  error: function() {
    return console.log("Error: user.admin should be in the local db.");
  }
});

if (!langChoice) {
  langChoice = 'pt';
  $.cookie('langChoice', langChoice);
}

deferred = fetchTranslation(langChoice);

deferred.done(function() {
  return console.log("Got translation.");
});
