// Generated by CoffeeScript 1.6.3
var deferred, fetchTranslation;

window.polyglot = new Polyglot();

window.polyglot.extend({
  "Home": "Início"
});

Handlebars.registerHelper('polyglot', function(phrase) {
  return window.polyglot.t(phrase);
});

fetchTranslation = function(languge) {
  var deferred, translation;
  deferred = $.Deferred();
  translation = new Translation({
    _id: languge
  });
  translation.fetch({
    success: function(record) {
      var json;
      json = record.toJSON();
      window.polyglot = new Polyglot();
      window.polyglot.extend(json);
      Handlebars.registerHelper('polyglot', function(phrase) {
        return window.polyglot.t(phrase);
      });
      return deferred.resolve();
    },
    error: function(error, response) {
      return console.log("Unable to fetch translation for " + " languge:" + languge + " model:" + JSON.stringify(error) + " response: " + response);
    }
  });
  return deferred.promise();
};

deferred = fetchTranslation("pt");

deferred.done(function() {
  return console.log("Got translation.");
});
