// Generated by CoffeeScript 1.6.2
(function(doc) {
    if (doc.collection === "user" || doc.collection === "question") {
        return emit(doc.id, null);
    }
});

/*
 //@ sourceMappingURL=map.map
 */