// Generated by CoffeeScript 1.6.3
var HomeView, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

HomeView = (function(_super) {
  __extends(HomeView, _super);

  function HomeView() {
    this.render = __bind(this.render, this);
    _ref = HomeView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HomeView.prototype.el = '#content';

  HomeView.prototype.addOne = function(result) {
    var recordView, rendered;
    recordView = new HomeRecordView({
      model: result
    });
    rendered = recordView.render();
    return $("#content table tbody").append(rendered);
  };

  HomeView.prototype.render = function() {
    this.$el.html("              <table class='summary tablesorter'>                <thead><tr>                  <th>Question</th>                  <th>User</th>                  <th>Last Modified</th>                </tr></thead>                <tbody>                </tbody>              </table>        ");
    return Coconut.homeView.results.each(this.addOne);
  };

  return HomeView;

})(Backbone.View);
