// Generated by CoffeeScript 1.6.3
var HomeRecordView, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

HomeRecordView = (function(_super) {
  __extends(HomeRecordView, _super);

  function HomeRecordView() {
    this.render = __bind(this.render, this);
    _ref = HomeRecordView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HomeRecordView.prototype.tagName = 'tr';

  HomeRecordView.prototype.render = function() {
    return this.$el.html("    <td><a href=\"/#show/case/" + (this.model.get("_id")) + "\">" + (this.model.get("question")) + "</a></td><td>" + (this.model.get("user")) + "</td>                    <td>" + (this.model.get("lastModifiedAt")) + "</td>            ");
  };

  return HomeRecordView;

})(Backbone.View);
