// Generated by CoffeeScript 1.6.3
var HomeRecordView;

HomeRecordView = Backbone.Marionette.CompositeView.extend({
  tagName: 'tr',
  template: JST["_attachments/templates/HomeRecordView.handlebars"],
  initialize: function() {
    return this.listenTo(this.collection, 'all', this.update);
  }
});
