// Generated by CoffeeScript 1.6.3
var HomeCompositeView;

HomeCompositeView = Backbone.Marionette.CompositeView.extend({
  childView: HomeRecordItemView,
  childViewContainer: '#records',
  template: JST["_attachments/templates/HomeView.handlebars"]
});
