// Generated by CoffeeScript 1.6.3
var ReportCompositeView;

ReportCompositeView = Backbone.Marionette.CompositeView.extend({
  childView: ReportRecordItemView,
  childViewContainer: '#records',
  template: JST["_attachments/templates/ReportView.handlebars"]
});
