// Generated by CoffeeScript 1.6.3
var ReportRecordItemView;

ReportRecordItemView = Backbone.Marionette.ItemView.extend({
  tagName: 'tr',
  template: JST["_attachments/templates/ReportRecordItemView.handlebars"]
});
