// Generated by CoffeeScript 1.6.3
var StaticView;

StaticView = Backbone.Marionette.ItemView.extend({
  template: JST["_attachments/templates/StatcView.handlebars"],
  ui: {
    checkboxes: "input[type=checkbox]"
  },
  events: {
    "click #scanRetry": "scanRetry",
    "click #register": "register",
    "click #registrationLink": "displayUserScanner",
    "click #newReportLink": "newReportLink"
  },
  initialize: function() {},
  scanRetry: function() {
    console.log("scanRetry");
    if (this.user !== null) {
      Coconut.trigger("displayUserScanner");
    } else {
      Coconut.trigger("displayAdminScanner");
    }
  },
  displayUserScanner: function() {
    console.log("displayUserScanner");
    Coconut.trigger("displayUserScanner");
  },
  register: function() {
    console.log("register");
    if (this.user !== null) {
      Coconut.trigger("displayUserRegistrationForm");
    } else {
      Coconut.trigger("displayAdminRegistrationForm");
    }
  },
  submitRegistration: function() {
    console.log("submitRegistration");
    Coconut.trigger("displayUserRegistrationForm");
  },
  newReportLink: function() {
    console.log("newReportLink");
    Coconut.trigger("displayReportMenu");
  }
});
