// Generated by CoffeeScript 1.3.1

(function(document) {
  if (document.collection === "result") {
    if (document.complete === "true") {
      return emit(document.question + ':true:' + document.lastModifiedAt, null);
    } else {
      return emit(document.question + ':false:' + document.lastModifiedAt, null);
    }
  }
});
