// Generated by CoffeeScript 1.6.3
var SecondaryIndexCollection, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SecondaryIndexCollection = (function(_super) {
  __extends(SecondaryIndexCollection, _super);

  function SecondaryIndexCollection() {
    _ref = SecondaryIndexCollection.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  SecondaryIndexCollection.prototype.model = Result;

  SecondaryIndexCollection.prototype.url = '/result';

  SecondaryIndexCollection.prototype.parse = function(result) {
    return _.pluck(result.rows, 'doc');
  };

  SecondaryIndexCollection.prototype.notSent = function() {
    return this.filter(function(result) {
      var _ref1;
      return !((_ref1 = result.get("sentTo")) != null ? _ref1.length : void 0);
    });
  };

  SecondaryIndexCollection.prototype.filteredByQuestionCategorizedByStatus = function(questionType) {
    var returnObject;
    returnObject = {};
    returnObject.complete = [];
    returnObject.notCompete = [];
    this.each(function(result) {
      if (result.get("question") !== questionType) {
        return;
      }
      switch (result.get("complete")) {
        case true:
          return returnObject.complete.push(result);
        default:
          return returnObject.notComplete.push(result);
      }
    });
    return returnObject;
  };

  SecondaryIndexCollection.prototype.filterByQuestionType = function(questionType) {
    return this.filter(function(result) {
      return result.get("question") === questionType;
    });
  };

  SecondaryIndexCollection.prototype.partialResults = function(questionType) {
    return this.filter(function(result) {
      return result.get("question") === questionType && !result.complete();
    });
  };

  return SecondaryIndexCollection;

})(Backbone.Collection);
