// Generated by CoffeeScript 1.3.3
var Sync,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Sync = (function(_super) {

  __extends(Sync, _super);

  function Sync() {
    this.replicateApplicationDocs = __bind(this.replicateApplicationDocs, this);

    this.replicateDesignDoc = __bind(this.replicateDesignDoc, this);

    this.getFromCloud = __bind(this.getFromCloud, this);

    this.log = __bind(this.log, this);

    this.last_get_time = __bind(this.last_get_time, this);

    this.last_get = __bind(this.last_get, this);

    this.last_send_time = __bind(this.last_send_time, this);

    this.last_send = __bind(this.last_send, this);
    return Sync.__super__.constructor.apply(this, arguments);
  }

  Sync.prototype.initialize = function() {
    return this.set({
      _id: "SyncLog"
    });
  };

  Sync.prototype.url = "/sync";

  Sync.prototype.last_send = function() {
    var _ref;
    return (_ref = this.get("last_send_result")) != null ? _ref.history[0] : void 0;
  };

  Sync.prototype.last_send_time = function() {
    var result, _ref;
    result = this.get("last_send_time") || ((_ref = this.last_send) != null ? _ref.start_time : void 0);
    if (result) {
      return moment(result).fromNow();
    } else {
      return "never";
    }
  };

  Sync.prototype.last_get = function() {
    return this.get("last_get_log");
  };

  Sync.prototype.last_get_time = function() {
    var result;
    result = this.get("last_get_time");
    if (result) {
      return moment(this.get("last_get_time")).fromNow();
    } else {
      return "never";
    }
  };

  Sync.prototype.sendToCloud = function(options) {
    var _this = this;
    return this.fetch({
      success: function() {
        var resultCollection;
        $(".sync-sent-status").html("pending");
        switch (Coconut.config.get("sync_mode")) {
          case "couchdb-sync":
            return $.couch.replicate(Coconut.config.database_name(), Coconut.config.cloud_url_with_credentials(), {
              success: function(response) {
                _this.save({
                  last_send_result: response
                });
                return options.success();
              },
              error: function() {
                return options.error();
              }
            });
          case "http-post":
            resultCollection = new ResultCollection();
            return resultCollection.fetch({
              success: function() {
                var notSentResults, saveSyncLog;
                notSentResults = resultCollection.notSent();
                saveSyncLog = _.after(notSentResults.length, function() {
                  return _this.save({
                    last_send_time: new Date()
                  }, Coconut.menuView.update(), $(".sync-sent-status").html("a few seconds ago"));
                });
                return _.each(resultCollection.notSent(), function(result) {
                  return $.ajax({
                    type: "POST",
                    url: Coconut.config.get("http-post-target"),
                    data: result.toJSON(),
                    success: function() {
                      result.set("sentTo", Coconut.config.get("http-post-target"));
                      if (Coconut.config.get("completion_mode") === "on-send") {
                        result.set("complete", "true");
                      }
                      result.save();
                      return saveSyncLog();
                    },
                    error: function(error) {
                      return $(".sync-sent-status").html("Error saving to " + (Coconut.config.get("http-post-target")) + ": " + (JSON.stringify(error)));
                    }
                  });
                });
              }
            });
        }
      }
    });
  };

  Sync.prototype.log = function(message) {
    Coconut.debug(message);
    $(".sync-get-status").html(message);
    return $("#message").append(message + "<br/>");
  };

  Sync.prototype.getFromCloud = function(options) {
    var _this = this;
    return this.fetch({
      success: function() {
        return $.couch.login({
          name: Coconut.config.get("local_couchdb_admin_username"),
          password: Coconut.config.get("local_couchdb_admin_password"),
          complete: function() {
            _this.log("Updating application design document...");
            return _this.replicateDesignDoc({
              success: function() {
                _this.log("Updating user accounts and question sets...");
                return _this.replicateApplicationDocs({
                  success: function() {
                    $.couch.logout();
                    _this.log("Finished");
                    _this.save({
                      last_get_time: new Date().getTime()
                    });
                    if (options != null) {
                      if (typeof options.success === "function") {
                        options.success();
                      }
                    }
                    return document.location.reload();
                  },
                  error: function(error) {
                    $.couch.logout();
                    return _this.log("Error updating application: " + error);
                  }
                });
              },
              error: function(error) {
                $.couch.logout();
                return _this.log("Error updating design document");
              }
            });
          },
          error: function(error) {
            return _this.log("Error logging in as local admin: " + error + ", trying to proceed anyway in case we are in admin party");
          }
        });
      }
    });
  };

  Sync.prototype.getNewNotifications = function(options) {
    return $.couch.db(Coconut.config.database_name()).view(("" + (Coconut.config.design_doc_name()) + "/rawNotificationsConvertedToCaseNotifications")({
      descending: true,
      include_docs: true,
      limit: 1,
      success: function(result) {
        var healthFacilities, mostRecentNotification, url, _ref, _ref1;
        mostRecentNotification = (_ref = result.rows) != null ? (_ref1 = _ref[0]) != null ? _ref1.doc.date : void 0 : void 0;
        url = "" + (Coconut.config.cloud_url_with_credentials()) + "/_design/" + (Coconut.config.database_name()) + "/_view/notifications?&ascending=true&include_docs=true&skip=1";
        if (mostRecentNotification) {
          url += "&startkey=\"" + mostRecentNotification + "\"";
        }
        healthFacilities = WardHierarchy.allWards({
          district: User.currentUser.get("district")
        });
        if (User.currentUser.get("district") == null) {
          healthFacilities = [];
        }
        return $.ajax({
          url: url,
          dataType: "jsonp",
          success: function(result) {
            _.each(result.rows, function(row) {
              var notification;
              notification = row.doc;
              if (_.include(healthFacilities, notification.hf)) {
                result = new Result({
                  question: "Case Notification",
                  MalariaCaseID: notification.caseid,
                  FacilityName: notification.hf,
                  Shehia: notification.shehia,
                  Name: notification.name
                });
                result.save();
                notification.hasCaseNotification = true;
                return $.couch.db(Coconut.config.database_name()).saveDoc(notification);
              }
            });
            return typeof options.success === "function" ? options.success() : void 0;
          }
        });
      }
    }));
  };

  Sync.prototype.replicate = function(options) {
    return $.couch.login({
      name: Coconut.config.get("local_couchdb_admin_username"),
      password: Coconut.config.get("local_couchdb_admin_password"),
      complete: function() {
        return $.couch.replicate(Coconut.config.cloud_url_with_credentials(), Coconut.config.database_name(), {
          success: function() {
            return options.success();
          },
          error: function() {
            return options.error();
          }
        }, options.replicationArguments);
      },
      error: function() {
        return console.log("Unable to login as local admin for replicating the design document (main application),  trying to proceed anyway in case we are in admin party.");
      }
    });
  };

  Sync.prototype.replicateDesignDoc = function(options) {
    return this.replicate(_.extend(options, {
      replicationArguments: {
        doc_ids: ["_design/" + Backbone.couch_connector.config.ddoc_name]
      }
    }));
  };

  Sync.prototype.replicateApplicationDocs = function(options) {
    return this.replicate(_.extend(options, {
      replicationArguments: {
        filter: "" + Backbone.couch_connector.config.ddoc_name + "/docsForApplication"
      }
    }));
  };

  return Sync;

})(Backbone.Model);
