// Generated by CoffeeScript 1.3.1
var WardHierarchy;

WardHierarchy = (function() {

  WardHierarchy.name = 'WardHierarchy';

  function WardHierarchy() {}

  WardHierarchy.hierarchy = {
    "URBAN WEST": {
      "URBAN": {
        "CHUMBUNI": ["CHUMBUNI", "KARAKANA", "MUEMBE MAKUMBI"],
        "KWAHANI": ["KIDONGO CHEKUNDU", "KWAALAMSHA", "KWAHANI", "MIKUNGUNI", "MUUNGANO"],
        "AMANI": ["AMANI", "KILIMAHEWA BONDENI", "KILIMAHEWA JUU", "SEBLENI"],
        "MJI MKONGWE": ["KIPONDA", "MALINDI", "MCHANGANI", "MKUNAZINI", "MWEMBETANGA", "SHANGANI", "VIKOKOTONI"],
        "RAHA LEO": ["GULIONI", "MAKADARA", "MLANDEGE", "MUEMBE LADU", "MWEMBESHAURI", "RAHALEO"],
        "KIKWAJUNI": ["KIKWAJUNI BONDENI", "KIKWAJUNI JUU", "KILIMANI", "KISIMA MAJONGOO", "MIEMBENI"],
        "JANG'OMBE": ["JANG'OMBE", "KWAALINATOO", "MATARUMBETA", "URUSI"],
        "MPENDAE": ["MEYA", "MIGOMBANI", "MPENDAE"],
        "MAGOMENI": ["KWA WAZEE", "MAGOMENI", "NYERERE", "SOGEA"],
        "KWAMTIPURA": ["KWAMTIPURA", "MKELE", "SHAURIMOYO"]
      },
      "WEST": {
        "MFENESINI": ["CHUINI", "KAMA", "KIHINANI", "MBUZINI", "MFENESINI", "MWAKAJE"],
        "MAGOGONI": ["KINUNI", "MAGOGONI", "WELEZO"],
        "DOLE": ["BUMBWISUDI", "DOLE", "KIANGA", "KIZIMBANI", "MTUFAANI", "MWERA"],
        "MWANAKWEREKWE": ["MELINNE", "MWANAKWEREKWE"],
        "FUONI": ["FUONI KIBONDENI", "FUONI KIJITOUPELE", "MAUNGANI", "PANGAWE"],
        "DIMANI": ["BWELEO", "DIMANI", "FUMBA", "KISAUNI", "KOMBENI", "MOMBASA", "SHAKANI", "TOMONDO"],
        "MTONI": ["KIDATU", "MTONI", "MTOPEPO"],
        "BUBUBU": ["BUBUBU", "KIBWENI", "MWANYANYA", "SHARIFU MSA"],
        "KIEMBESAMAKI": ["CHUKWANI", "KIEMBESAMAKI"]
      }
    },
    "SOUTH PEMBA": {
      "MKOANI": {
        "MTAMBILE": ["KANGANI", "KENGEJA", "MJIMBINI", "MTAMBILE"],
        "KIWANI": ["KIWANI", "MTANGANI", "MWAMBE", "SHAMIANI MWAMBE"],
        "MKOANI": ["CHUMBAGENI", "MAKOMBENI", "MAKOONGWE", "MBUGUANI", "NG'OMBENI", "UWELENI", "WAMBAA"],
        "MKANYAGENI": ["CHOKOCHO", "KISIWA PANZA", "MICHENZANI", "MKANYAGENI", "SHIDI"],
        "CHAMBANI": ["CHAMBANI", "MIZINGANI", "NGWACHANI", "UKUTINI"]
      },
      "CHAKECHAKE": {
        "ZIWANI": ["KWALE", "MBUZINI", "NDAGONI", "WARA", "ZIWANI"],
        "CHONGA": ["CHONGA", "DODO", "KILINDI", "MATALE", "MGELEMA", "NGOMENI", "PUJINI"],
        "CHAKECHAKE": ["CHACHANI", "CHANJAANI", "SHUNGI", "TIBIRINZI", "WESHA"],
        "WAWI": ["MVUMONI", "NG'AMBWA", "UWANDANI", "VITONGOJI", "WAWI"]
      }
    },
    "NORTH UNGUJA": {
      "NORTH B": {
        "DONGE": ["DONGE KARANGE", "DONGE KIPANGE", "DONGE MBIJI", "DONGE MCHANGANI", "DONGE MNYIMBI", "DONGE MTAMBILE", "DONGE VIJIBWENI", "MAHONDA", "MUWANDA"],
        "BUMBWINI": ["KIDANZINI", "MAFUFUNI", "MAKOBA", "MANGAPWANI", "MISUFINI", "ZINGWEZINGWE"],
        "KITOPE": ["FUJONI", "KILOMBERO", "KINDUNI", "KIOMBA MVUA", "KITOPE", "KIWENGWA", "MATETEMA", "MBALENI", "MGAMBO", "MKADINI", "PANGENI", "UPENJA"]
      },
      "NORTH A": {
        "CHAANI": ["BANDAMAJI", "CHAANI KUBWA", "CHAANI MASINGINI", "CHUTAMA", "GAMBA", "KINYASINI", "KISONGONI", "MCHENZASHAURI", "MOGA"],
        "TUMBATU": ["MKOKOTONI", "MTO WA PWANI", "PALE", "PITANAZAKO", "TUMBATU GOMANI", "TUMBATU JONGOWE"],
        "MKWAJUNI": ["KIBENI", "KIVUNGE", "MKWAJUNI", "MUWANGE", "POTOA"],
        "NUNGWI": ["FUKUCHANI", "KIDOTI", "KIGUNDA", "KILIMANI", "KILINDI", "NUNGWI", "TAZARI"],
        "MATEMWE": ["KANDWI", "KIJINI", "KIKOBWENI", "MATEMWE", "PWANI MCHANGANI"]
      }
    },
    "SOUTH UNGUJA": {
      "SOUTH": {
        "MUYUNI": ["BWEJUU", "JAMBIANI KIBIGIJA", "JAMBIANI KIKADINI", "KITOGANI", "MUUNGONI", "MUYUNI A", "MUYUNI B", "MUYUNI C", "PAJE", "PETE"],
        "MAKUNDUCHI": ["KAJENGWA", "KIBUTENI", "KIJINI", "KIZIMKAZI DIMBANI", "KIZIMKAZI MKUNGUNI", "MTENDE", "MZURI", "NGANANI"]
      },
      "CENTRAL": {
        "UZINI": ["BAMBI", "GHANA", "KIBOJE MKWAJUNI", "KIBOJE MWEMBESHAURI", "MCHANGANI", "MGENI HAJI", "MITAKAWANI", "MIWANI", "MPAPA", "PAGALI", "TUNDUNI", "UMBUJI", "UZINI"],
        "KOANI": ["BINGUNI", "BUNGI", "JUMBI", "KIDIMNI", "KIKUNGWI", "KOANI", "MACHUI", "NG'AMBWA", "TUNGUU", "UBAGO", "UNGUJA UKUU KAEBONA", "UNGUJA UKUU KAEPWANI", "UZI"],
        "CHWAKA": ["CHARAWE", "CHEJU", "CHWAKA", "DUNGA BWENI", "DUNGA KIEMBENI", "JENDELE", "MARUMBI", "MICHAMVI", "NDIJANI", "PONGWE", "UKONGORONI", "UROA"]
      }
    },
    "NORTH PEMBA": {
      "WETE": {
        "GANDO": ["BOPWE", "FUNDO", "GANDO", "KIZIMBANI", "UKUNJWI"],
        "WETE": ["JADIDA", "KIPANGANI", "PANDANI", "SELEMU", "UTAANI"],
        "MTAMBWE": ["KISIWANI", "MTAMBWE KASKAZINI", "MTAMBWE KUSINI", "PIKI"],
        "KOJANI": ["KIUNGONI", "KOJANI", "MCHANGAMDOGO", "SHENGEJUU"],
        "OLE": ["KAMBINI", "KANGAGANI", "KIUYU MINUNGWINI", "MJINI OLE", "OLE"]
      },
      "MICHEWENI": {
        "KONDE": ["KIFUNDI/MATANGATWANI", "KONDE", "MAKANGALE", "MSUKA"],
        "TUMBE": ["KINOWE", "SHUMBA VIAMBONI", "SIZINI", "TUMBE"],
        "MICHEWENI": ["KIUYU MAZIWANG'OMBE", "KIUYU MBUYUNI", "MICHEWENI", "MJINI WINGWI", "SHUMBA MJINI"],
        "MGOGONI": ["FINYA", "KINYASINI", "MGOGONI", "WINGWI MAPOFU", "WINGWI MTEMANI", "WINGWI NJUGUNI"]
      }
    }
  };

  WardHierarchy.byWard = function(targetWard) {
    var result;
    result = {};
    _.each(WardHierarchy.hierarchy, function(districts, region) {
      return _.each(districts, function(constituans, district) {
        return _.each(constituans, function(wards, constituan) {
          return _.each(wards, function(ward) {
            if (ward === targetWard) {
              return result = {
                region: region,
                district: district,
                constituan: constituan
              };
            }
          });
        });
      });
    });
    return result;
  };

  WardHierarchy.region = function(ward) {
    return WardHierarchy.byWard(ward).region;
  };

  WardHierarchy.district = function(ward) {
    return WardHierarchy.byWard(ward).district;
  };

  WardHierarchy.constituan = function(ward) {
    return WardHierarchy.byWard(ward).constituan;
  };

  WardHierarchy.ward = function(ward) {
    return ward;
  };

  WardHierarchy.shehia = function(shehia) {
    return shehia;
  };

  WardHierarchy.allRegions = function() {
    return _.sortBy(_.keys(WardHierarchy.hierarchy), function(region) {
      return region;
    });
  };

  WardHierarchy.allDistricts = function() {
    return _.chain(_.map(WardHierarchy.hierarchy, function(districts, region) {
      return _.keys(districts);
    })).flatten().sortBy(function(district) {
      return district;
    }).value();
  };

  WardHierarchy.allConstituans = function() {
    return _.chain(_.map(WardHierarchy.hierarchy, function(districts, region) {
      return _.map(districts, function(constituans, district) {
        return _.keys(constituans);
      });
    })).flatten().sortBy(function(constituan) {
      return constituan;
    }).value();
  };

  WardHierarchy.allWards = function(options) {
    if (options == null) {
      options = {};
    }
    return _.chain(_.map(WardHierarchy.hierarchy, function(districts, region) {
      if (options.region) {
        if (region !== options.region) {
          return;
        }
      }
      return _.map(districts, function(constituans, district) {
        if (options.district) {
          if (district !== options.district) {
            return;
          }
        }
        return _.map(constituans, function(wards, constituan) {
          if (options.constituan) {
            if (constituan !== options.constituan) {
              return;
            }
          }
          return wards;
        });
      });
    })).flatten().compact().sortBy(function(ward) {
      return ward;
    }).value();
  };

  return WardHierarchy;

})();
