// Generated by CoffeeScript 1.3.1

(function(doc, req) {
  var healthFacility, _i, _len, _ref;
  if (doc.hf && doc.caseid) {
    _ref = req.query.healthFacilities.split(",");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      healthFacility = _ref[_i];
      if (doc.hf === healthFacility) {
        return true;
      }
    }
  } else if (doc._id === ("_design/" + Backbone.couch_connector.config.ddoc_name)) {
    return true;
  } else if (doc.collection === "question") {
    return true;
  } else {
    return false;
  }
});
