// Generated by CoffeeScript 1.3.1

(function(doc, req) {
  var healthFacility, _i, _len, _ref;
  if (doc.hf && doc.caseid) {
    _ref = req.query.healthFacilities.split(",");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      healthFacility = _ref[_i];
      if (doc.hf === healthFacility) {
        return true;
      }
    }
  }
  return false;
});
