// Generated by CoffeeScript 1.7.1
(function(doc, req) {
  if (doc.collection === 'question' || doc.collection === 'user') {
    return true;
  } else {
    return false;
  }
});

//# sourceMappingURL=docsForApplication.map
